before_script:
- apt-get update -qq
- apt-get install -qq bubblewrap
- echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init
- opam switch create 4.07.0
- opam install dune
- opam install base
- opam install stdio
- opam install ppx_jane
- opam install menhir
- eval $(opam env)

build_job:
  stage: build
  script:
  - dune build app/main.exe

test_job:
  stage: test
  script:
  - dune runtest

cache:
  paths:
  - .opam
