before_script:
- apt-get update -qq
- apt-get install -qq bubblewrap
- apt-get install -qq unzip
- echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init -c 4.07.0 --root=.opam
- opam install -y -q --root=.opam dune
- opam install -y -q --root=.opam base
- opam install -y -q --root=.opam stdio
- opam install -y -q --root=.opam ppx_jane
- opam install -y -q --root=.opam menhir
- opam install -y -q --root=.opam odoc
- eval $(opam env --root=.opam)

build:
  stage: build
  script:
  - dune build app/main.exe
  artifacts:
    paths:
    - _build

test:
  stage: test
  script:
  - dune runtest

pages:
  stage: deploy
  script:
  - dune build @doc
  - mv _build/main/_doc/_html public
  artifacts:
    paths:
    - public
  only:
  - master

cache:
  paths:
  - .opam
