before_script:
- apt-get update -qq
- apt-get install -qq bubblewrap
- apt-get install -qq unzip
- echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init -c 4.07.0 --root=./.opam
- eval $(opam env --root=/builds/emelle/emelle/.opam)
- opam install -y -q dune
- opam install -y -q base
- opam install -y -q stdio
- opam install -y -q ppx_jane
- opam install -y -q menhir
- opam install -y -q odoc

build:
  stage: build
  script:
  - dune build app/main.exe
  artifacts:
    paths:
    - _build

test:
  stage: test
  script:
  - dune runtest

pages:
  stage: deploy
  script:
  - dune build @doc
  - mv _build/main/_doc/_html public
  artifacts:
    paths:
    - public
  only:
  - master

cache:
  paths:
  - .opam
