before_script:
- apt-get update -qq
- apt-get install -qq bubblewrap
- apt-get install -qq unzip
- echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init
- opam switch create 4.07.0
- opam install -y -q dune
- opam install -y -q base
- opam install -y -q stdio
- opam install -y -q ppx_jane
- opam install -y -q menhir
- eval $(opam env)

build_job:
  stage: build
  script:
  - dune build app/main.exe

test_job:
  stage: test
  script:
  - dune runtest

cache:
  paths:
  - .opam
